#Generated by LISAv2
ib_nic="eth0"
nbc_ppn=2
mpi_settings="-TCP -np2 -hostlist host1:1,host2:1"
imb_mpi1_tests="pingpong"
mpi_type="ibm"
imb_nbc_tests_iterations=1
imb_nbc_tests="all"
imb_rma_tests_iterations=1
imb_rma_tests="all"
mpi1_ppn=2
rma_ppn=2
imb_mpi1_tests_iterations=2
